### ISSUE TITLE
Play button not shows

### ISSUE THREAD

**Issue by sp213** [sadiqmmm/plyr-rails#1]
Hi, 

thanks for your gem, which is really awesome. But there is one problem, the play button not shows up after all the setups done, following the instructions.

![snip20161208_3](https://cloud.githubusercontent.com/assets/4160306/20999925/e01ae662-bd52-11e6-940a-cc7ae5ec1543.png)

**Comment by sadiqmmm** [comment]
Thank you for reporting the problem.

This problem has been fixed now 👍 

Please "bundle update" your rails app to update latest version of the gem.

**Comment by sp213** [comment]
Thanks for fixing this! I'll have a try later on! 

Thumbs up!
