### ISSUE TITLE
There is a bug used in mobile

### ISSUE THREAD

**Issue by SnugNest** [sadiqmmm/plyr-rails#5]
ex. When used in iphone, the width of the plyr don't suit.
ex. When used in PC, the class of the div have "plyr plyr--video plyr--is-touch plyr--fullscreen-enabled plyr--stopped plyr--ready", but When used in the iphone 6 , the class of the div only have "plyr--ready"

**Comment by sadiqmmm** [comment]
Thanks for reporting.
Gem upgraded to v3.3.7
