### ISSUE TITLE
Should this gem be upgraded to latest version of plyr (v3.5.6)?

### ISSUE THREAD

**Issue by iraszl** [sadiqmmm/plyr-rails#8]
@sadiqmmm There are some really good fixes in v3.5+. I'd love to help if you guide me. Let me know!

**Comment by iraszl** [comment]
Here is a fork that has already been upgraded: https://github.com/ludalex/plyr-rails

**Comment by yesthatguy** [comment]
+1 would love to see the latest version available (currently 3.5.7).

@sadiqmmm I see that @ludalex has already sent a PR but in case there's anything missing in that if you're able to document the steps you go through to upgrade it in the README or a CONTRIBUTING.md file I and others in the community would be happy to handle the bulk of the work to keep this up to date and you can just approve changes or delegate to someone else who can verify PRs and merge them in.

**Comment by sadiqmmm** [comment]
Update with the PR
